# Updates the Priority field on a Project board when a [Pri] label gets added to an issue.

name: Keep priority labels in sync

# Controls when the workflow will run
on:
  # Triggers the workflow when labels are added to an issue
  issues:
    types:
      - labeled

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_labels:
    runs-on: ubuntu-latest
    steps:
    - name: check juice with bash
      run: |
          for item in "${{ github.event.issue.labels.*.name }}"
          do
            echo $item
            if [[ "$item" == "[Pri] Low" ]]; then
              echo "Low"
            fi
            if [[ "$item" == "[Pri] Normal" ]]; then
              echo "Normal"
            fi
          done

  # Updates the Priority field with the appropriate priority level
  check_priority: 
    if: |
      contains(github.event.issue.labels.*.name, '[Pri] TBD') || 
      contains(github.event.issue.labels.*.name, '[Pri] Low') || 
      contains(github.event.issue.labels.*.name, '[Pri] Normal') ||
      contains(github.event.issue.labels.*.name, '[Pri] High') ||
      contains(github.event.issue.labels.*.name, '[Pri] BLOCKER')

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }} 

      - name: Read status
        id: read_status
        uses: github/update-project-action@v2
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          organization: johns-test-org
          project_number: 1
          operation: read
          field: Priority
          content_id: ${{ github.event.issue.node_id }}
          value: Low
      - name: Output status
        run: |
          echo "Current status value: ${{ steps.read_status.outputs.field_read_value }}"
#       - name: Update status
#         id: update_status
#         uses: github/update-project-action@v2
#         with:
#           github_token: ${{ steps.generate_token.outputs.token }}
#           organization: johns-test-org
#           project_number: 1
#           content_id: ${{ github.event.issue.node_id }}
#           field: Priority
#           value: High
          
      
